### ISSUE TITLE
Update lesson maintainers membership

### ISSUE THREAD

**Issue by ewallace** [carpentries-lab/good-enough-practices#125]
To add lesson maintainers (@ameynert, @emma-wilson, @alee) to the [maintainers team list](https://github.com/orgs/carpentries-incubator/teams/good-enough-practices-maintainers/members)

We need to:
- EITHER make them members of carpentries-incubator organization
- OR first transition the lesson to carpentries-lab then make them members of the relevant organization

Related to #124

**Comment by emma-wilson** [comment]
Hi, just looking for an update on this. Let me know if there is anything I need to do on my end

**Comment by ewallace** [comment]
@tobyhodges @zkamvar could we request your help on adding maintainers via carpentries-lab organi`ation?

**Comment by tobyhodges** [comment]
I had to create a new team in the carpentries-lab organisation, which I have invited the folks named above to join. I will delete the old maintainer team in the Incubator, since it has no lesson repository to be associated with after the repo transfer.
