### ISSUE TITLE
Mint a zenodo doi for a release of the lesson

### ISSUE THREAD

**Issue by ewallace** [carpentries-lab/good-enough-practices#126]
This is to be done after move of the lesson to carpentries-lab, see https://github.com/carpentries-lab/reviews/issues/24#issuecomment-1637894051

**Comment by tobyhodges** [comment]
When you do this it would be great if you would list the reviewers as Contributors in the Zenodo record. At the moment, Zenodo does not provide "Reviewer" as an option for the type of contributor, so "Other" is probably best for now. I hope they will introduce something like "Reviewer" in future (perhaps "Writing - review & editing" from [the CRediT system](https://credit.niso.org/)?).
