### ISSUE TITLE
Maintainers to update local repos and forks

### ISSUE THREAD

**Issue by ewallace** [carpentries-lab/good-enough-practices#127]
We just transitioned the lesson to new lesson infrastructure carpentries workbench, see #123 

As part of this, maintainers should update local repository to avoid any possible problems. See https://github.com/carpentries/lesson-transition/tree/main#beta-phase
The easiest way is to delete the repository and clone fresh. 

It's also helpful to delete forks and re-fork, see https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

I'm suggesting this for all maintainers
- [x] @ewallace (me)
- [ ] @ameynert 
- [x] @emma-wilson 
- [x] @alee

**Comment by emma-wilson** [comment]
Only made edits via GitHub web interface (no local copy) and though branches on the repo (no forks) so should be good but thanks for the heads up

**Comment by ewallace** [comment]
Closing this as out of date.
