### ISSUE TITLE
Link to Wilson paper is broken

### ISSUE THREAD

**Issue by ameynert** [carpentries-lab/good-enough-practices#137]
https://carpentries-lab.github.io/good-enough-practices/05-project_organization.html

Link at bottom of page.

**Comment by alee** [comment]
right now it looks like it goes to the github repository:

 https://github.com/swcarpentry/good-enough-practices-in-scientific-computing

Should it go here instead?

 https://swcarpentry.github.io/good-enough-practices-in-scientific-computing/

**Comment by ameynert** [comment]
This episode was adapted from and includes material from Wilson et al. [Good Enough Practices for Scientific Computing](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing). 

Link should be: https://doi.org/10.1371/journal.pcbi.1005510
